### ISSUE TITLE
An error occurred while activating the extension: Cannot read properties of undefined (reading 'blockComment')

### ISSUE THREAD

**Issue by tmn73** [evyatar9/ExplainThisCode#1]
I wanted to try the extension.
When i select a line of code and use the keybinds it says

- An explanation of the selected code will be shown in the form of comments above it.
- An error occurred while activating the extension: Cannot read properties of undefined (reading 'blockComment')

The selected line is (tsx) but i have the same problem with every other line
```js 
if (isLoading || !provisioningRequest) return <Loading />;
```

**Comment by evyatar9** [comment]
Hi @mlfcnt,

Thank you for reaching out. I'm trying to understand the issue you're experiencing.
You're trying to use a .tsx file extension as [follows](https://ik.imagekit.io/evyatar9/tsx.gif)?
Is this issue happening in a specific programming language, or is it occurring across multiple languages?

Thanks!

**Comment by evyatar9** [comment]
Hi @mlfcnt,

Thank you for reaching out. I'm trying to understand the issue you're experiencing.
Are you trying to use the extension on ```.tsx``` file as [follows](https://ik.imagekit.io/evyatar9/tsx.gif)?
Is this issue only in ```.tsx``` files or is it occurring across multiple languages?

Thanks!

**Comment by tmn73** [comment]
Seems to be working now. My bad ! Thanks for the extension !
